FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json /app/

RUN npm ci

COPY . .

RUN ls -a

RUN npx vite build || exit 1

FROM node:20-alpine AS prod

WORKDIR /app

COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules/ /app/node_modules/

RUN npm i --omit dev


CMD ["node", "build/index.js"]